version: '3'

services:
  postgres:
    image: postgres:16
    ports:
      - 3000:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=test123456
      - POSTGRES_USER=as_admin
      - POSTGRES_DB=astart
