----- CREATE DATABASE: astart
CREATE DATABASE astart
	WITH
	OWNER = as_admin
	ENCODING = 'UTF8'
	LC_COLLATE = 'en_US.UTF-8'
	LC_CTYPE = 'en_US.UTF-8'
    CONNECTION LIMIT = -1
    IS_TEMPLATE = False;